In [1]:
import pandas as pd
df = pd.read_csv("311_Service_Requests.csv")
df.head()

/tmp/ipykernel_273/1316942104.py:2: DtypeWarning: Columns (49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("311_Service_Requests.csv")

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,32310363,12/31/2015 11:59:45 PM,01/01/2016 12:55:15 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034.0,71 VERMILYEA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)"
1,32309934,12/31/2015 11:59:44 PM,01/01/2016 01:26:57 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11105.0,27-07 23 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)"
2,32309159,12/31/2015 11:59:29 PM,01/01/2016 04:51:03 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10458.0,2897 VALENTINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)"
3,32305098,12/31/2015 11:57:46 PM,01/01/2016 07:43:13 AM,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,10461.0,2940 BAISLEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)"
4,32306529,12/31/2015 11:56:58 PM,01/01/2016 03:24:42 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373.0,87-14 57 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)"

In [2]:
df.shape

(163836, 53)

In [3]:
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough',
       'School Name', 'School Number', 'School Region', 'School Code',
       'School Phone Number', 'School Address', 'School City', 'School State',
       'School Zip', 'School Not Found', 'School or Citywide Complaint',
       'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
       'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
       'Bridge Highway Segment', 'Garage Lot Name', 'Ferry Direction',
       'Ferry Terminal Name', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163836 entries, 0 to 163835
Data columns (total 53 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique Key                      163836 non-null  int64
 1   Created Date                    163836 non-null  object
 2   Closed Date                     162835 non-null  object
 3   Agency                          163836 non-null  object
 4   Agency Name                     163836 non-null  object
 5   Complaint Type                  163836 non-null  object
 6   Descriptor                      160596 non-null  object
 7   Location Type                   163836 non-null  object
 8   Incident Zip                    162621 non-null  float64
 9   Incident Address                141044 non-null  object
 10  Street Name                     141044 non-null  object
 11  Cross Street 1                  138590 non-null  object
 12  Cross Street 2                  138363 non-null  object
 13  Intersection Street 1           22489 non-null   object
 14  Intersection Street 2           22262 non-null   object
 15  Address Type                    162500 non-null  object
 16  City                            162621 non-null  object
 17  Landmark                        186 non-null     object
 18  Facility Type                   162837 non-null  object
 19  Status                          163836 non-null  object
 20  Due Date                        163835 non-null  object
 21  Resolution Description          163836 non-null  object
 22  Resolution Action Updated Date  162848 non-null  object
 23  Community Board                 163836 non-null  object
 24  Borough                         163836 non-null  object
 25  X Coordinate (State Plane)      162142 non-null  float64
 26  Y Coordinate (State Plane)      162142 non-null  float64
 27  Park Facility Name              163835 non-null  object
 28  Park Borough                    163835 non-null  object
 29  School Name                     163835 non-null  object
 30  School Number                   163835 non-null  object
 31  School Region                   163835 non-null  object
 32  School Code                     163835 non-null  object
 33  School Phone Number             163835 non-null  object
 34  School Address                  163835 non-null  object
 35  School City                     163835 non-null  object
 36  School State                    163835 non-null  object
 37  School Zip                      163835 non-null  object
 38  School Not Found                163835 non-null  object
 39  School or Citywide Complaint    0 non-null       float64
 40  Vehicle Type                    0 non-null       float64
 41  Taxi Company Borough            0 non-null       float64
 42  Taxi Pick Up Location           0 non-null       float64
 43  Bridge Highway Name             150 non-null     object
 44  Bridge Highway Direction        150 non-null     object
 45  Road Ramp                       132 non-null     object
 46  Bridge Highway Segment          132 non-null     object
 47  Garage Lot Name                 0 non-null       float64
 48  Ferry Direction                 0 non-null       float64
 49  Ferry Terminal Name             1 non-null       object
 50  Latitude                        162142 non-null  float64
 51  Longitude                       162142 non-null  float64
 52  Location                        162142 non-null  object
dtypes: float64(11), int64(1), object(41)
memory usage: 66.2+ MB

In [5]:
df = df[['Created Date', 'Complaint Type', 'Descriptor', 'Borough', 'Latitude', 'Longitude']]

In [6]:
df.rename(columns = {'Created Date': 'date', 'Complaint Type' : 'category', 'Descriptor' : 'complaint', 'Borough' : 'location'}, inplace=True)

In [7]:
df = df.dropna()

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.to_csv("clean_complaints.csv", index=False)

In [10]:
df.head()

,date,category,complaint,location,Latitude,Longitude
0,12/31/2015 11:59:45 PM,Noise - Street/Sidewalk,Loud Music/Party,MANHATTAN,40.865682,-73.923501
1,12/31/2015 11:59:44 PM,Blocked Driveway,No Access,QUEENS,40.775945,-73.915094
2,12/31/2015 11:59:29 PM,Blocked Driveway,No Access,BRONX,40.870325,-73.888525
3,12/31/2015 11:57:46 PM,Illegal Parking,Commercial Overnight Parking,BRONX,40.835994,-73.828379
4,12/31/2015 11:56:58 PM,Illegal Parking,Blocked Sidewalk,QUEENS,40.733060,-73.874170

In [11]:
df.shape

(158946, 6)

In [12]:
df.isnull().sum()

date         0
category     0
complaint    0
location     0
Latitude     0
Longitude    0
dtype: int64